### ISSUE TITLE
/var/lib/gems/2.7.0/gems/wp2txt-1.0.1/lib/wp2txt/article.rb:41:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by vince62s** [yohasebe/wp2txt#10]
While running this command:
wp2txt -i eswiki-latest-pages-articles.xml.bz2 -o ./estext -x --no-title --no-heading --no-category --file-size=1000 --no-marker

got this error:
Decompressing and splitting the original dump file.
This may take a while. Please be patient!
Checking lbzip2: detected [/usr/bin/lbzip2]
▹▹▹▸▹ Time: 00:08:57
Complete!

Converting
Number of files being processed: 17
Number of CPU cores being used:  22
Traceback (most recent call last):===============================================================================================        | Time: 00:06:30
	20: from /usr/local/bin/wp2txt:23:in `<main>'
	19: from /usr/local/bin/wp2txt:23:in `load'
	18: from /var/lib/gems/2.7.0/gems/wp2txt-1.0.1/bin/wp2txt:113:in `<top (required)>'
	17: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
	16: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
	15: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
	14: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
	13: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
	12: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
	11: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
	10: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
	 9: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
	 8: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:557:in `process_incoming_jobs'
	 7: from /var/lib/gems/2.7.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
	 6: from /var/lib/gems/2.7.0/gems/wp2txt-1.0.1/bin/wp2txt:115:in `block in <top (required)>'
	 5: from /var/lib/gems/2.7.0/gems/wp2txt-1.0.1/lib/wp2txt.rb:294:in `extract_text'
	 4: from /var/lib/gems/2.7.0/gems/wp2txt-1.0.1/lib/wp2txt.rb:294:in `each'
	 3: from /var/lib/gems/2.7.0/gems/wp2txt-1.0.1/lib/wp2txt.rb:312:in `block in extract_text'
	 2: from /var/lib/gems/2.7.0/gems/wp2txt-1.0.1/lib/wp2txt.rb:312:in `new'
	 1: from /var/lib/gems/2.7.0/gems/wp2txt-1.0.1/lib/wp2txt/article.rb:41:in `initialize'
/var/lib/gems/2.7.0/gems/wp2txt-1.0.1/lib/wp2txt/article.rb:41:in `gsub!': invalid byte sequence in UTF-8 (ArgumentError)

**Comment by yohasebe** [comment]
Thank you for your report. I have confirmed that the error occurs with the latest eswiki dump file. I have released an updated gem (version 1.0.2), please `gem update wp2txt` and give it a try.

**Comment by vince62s** [comment]
hmm:
sudo gem update wp2txt
[sudo] password for vincent: 
Updating installed gems
Updating wp2txt
Fetching wp2txt-1.0.2.gem
Successfully installed wp2txt-1.0.2
Parsing documentation for wp2txt-1.0.2
Installing ri documentation for wp2txt-1.0.2
Installing darkfish documentation for wp2txt-1.0.2
Done installing documentation for wp2txt after 0 seconds
Parsing documentation for wp2txt-1.0.2
Done installing documentation for wp2txt after 0 seconds
Gems updated: wp2txt
then:
wp2txt -i eswiki-latest-pages-articles.xml.bz2 -o ./estext -x --no-title --no-heading --no-category --file-size=1000 --no-marker
Traceback (most recent call last):
	1: from /usr/local/bin/wp2txt:23:in `<main>'
/usr/local/bin/wp2txt:23:in `load': cannot load such file -- /var/lib/gems/2.7.0/gems/wp2txt-1.0.2/bin/wp2txt (LoadError)

but the file is there.
do I need to update anything else ?

**Comment by yohasebe** [comment]
I don't have a definite answer at the moment, but the ruby version (2.7.0) seems a bit too old to me. Updating ruby (3.1.0 or higher) and reinstalling the gem may help. What OS are you using?

**Comment by vince62s** [comment]
Ubuntu 20.04, will give a try
