### ISSUE TITLE
Tool doesn't work on small corpora

### ISSUE THREAD

**Issue by Erstyx** [yohasebe/wp2txt#13]
For corpora smaller than 10 MB (e.g. xhwiki-20220820-pages-articles.xml.bz2), the tool errors out with the message below. The issue can be worked around by specifying, e.g. "-f 5" (or whatever number will force a split).

▹▹▹▹▹E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/lib/wp2txt.rb:163:in `size': no implicit conversion of nil into String (TypeError)

      if File.size(outfilename).zero?
                   ^^^^^^^^^^^
        from E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/lib/wp2txt.rb:163:in `split_file'
        from E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/bin/wp2txt:88:in `run'
        from E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/bin/wp2txt:192:in `<top (required)>'
        from E:/Ruby32-x64/bin/wp2txt:32:in `load'
        from E:/Ruby32-x64/bin/wp2txt:32:in `<main>'

**Comment by yohasebe** [comment]
Thank you for your report! I have fixed the bug. Please check the latest version (1.1.2).
