### ISSUE TITLE
Failed to unzip and parse a dumped wiki file. Error: wp2txt-0.9.1/lib/wp2txt.rb:113:in `popen': No such file or directory - bzip2 -c -d enwiki.bz2 (Errno::ENOENT)

### ISSUE THREAD

**Issue by oattie** [yohasebe/wp2txt#3]
Hi Yoichiro,

When I run wp2txt -i enwiki.bz2, I got this error: wp2txt-0.9.1/lib/wp2txt.rb:113:in `popen': No such file or directory - bzip2 -c -d enwiki.bz2 (Errno::ENOENT)

Not sure, why I have got this error. The input is in the same location as wp2txt.

Can you please advise?

Many thanks.
Best regards,
AP

**Comment by yohasebe** [comment]
Hi!

Looks like bzip2 is not installed in your system. What OS are you running wp2txt on? If you are on MacOS with homebrew installed, `brew install bzip2` will probably fix the problem.

YH

**Comment by oattie** [comment]
Hello Yoichiro,

It works like a charm. 

Cheers,
AP

**Comment by rajnishkgaur** [comment]
> Hi Yoichiro,
> 
> When I run wp2txt -i enwiki.bz2, I got this error: wp2txt-0.9.1/lib/wp2txt.rb:113:in `popen': No such file or directory - bzip2 -c -d enwiki.bz2 (Errno::ENOENT)
> 
> Not sure, why I have got this error. The input is in the same location as wp2txt.
> 
> Can you please advise?
> 
> Many thanks.
> Best regards,
> AP

How did you solve this :
When I run wp2txt -i enwiki.bz2, I got this error: wp2txt-0.9.1/lib/wp2txt.rb:113:in `popen': No such file or directory - bzip2 -c -d enwiki.bz2 (Errno::ENOENT)

Thanks

**Comment by yohasebe** [comment]
Hi

The error message says bzip2 is not installed in your system. If you are on MacOS, for instance, you can install [homebrew](https://brew.sh/) first and run `brew install bzip2`. I'm sure it will fix the problem.

YH
