### ISSUE TITLE
Wrong titles extracted

### ISSUE THREAD

**Issue by itmammoth** [yohasebe/wp2txt#4]
Version: 0.9.1

Hi,

I found some extracted titles wrong, and which seems to occur occasionally.

To reproduce the bug:

Run `wp2txt` twice like below.
(The dump file I used is [jawiki-20190801-pages-articles1.xml-p1p106175.bz2](https://dumps.wikimedia.org/jawiki/20190801/jawiki-20190801-pages-articles1.xml-p1p106175.bz2))

```
$ wp2txt -i jawiki-20190801-pages-articles1.xml-p1p106175.bz2 -o output-1
# Do again into an another directory
$ wp2txt -i jawiki-20190801-pages-articles1.xml-p1p106175.bz2 -o output-2
```

After generating texts, compare a pair of files in each output directories.

Here are the wrong titles I found...

_output-1/jawiki-20190801-pages-articles1.xml-p1p106175-02.txt_
```
[[ひらまつつとむ]]

CATEGORIES: Compiling and linking, コンパイラ, プログラミング言語の実装, ソフトウェア開発ツール, 構文解析 (プログラミング)

コンパイラ（compiler）とは、コンピュータ・プログラミング言語の処理系（言語処理系）の一種で、高水準言語によるソースコードから、機械語あるいは元のプログラムよりも低い水準のコードに変換（コンパイル）するプログラムである。
```

_output-2/jawiki-20190801-pages-articles1.xml-p1p106175-02.txt_
```
[[コンパイラ]]

CATEGORIES: Compiling and linking, コンパイラ, プログラミング言語の実装, ソフトウェア開発ツール, 構文解析 (プログラミング)

コンパイラ（compiler）とは、コンピュータ・プログラミング言語の処理系（言語処理系）の一種で、高水準言語によるソースコードから、機械語あるいは元のプログラムよりも低い水準のコードに変換（コンパイル）するプログラムである。
```

`outpus-1`'s one is wrong title as you see.

I assume the bug is related with multi-threading taken in the version 0.9.1.
So far as I checked, all titles generated with `--num-threads=1` are correct.

Thanks!

**Comment by Gopal088** [comment]
Getting below error. Not sure whats the issue.

c:\Users\gopal\Downloads>wp2txt -i enwiki-20190820.bz2 -o wikitxt
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
Traceback (most recent call last):
        5: from C:/Ruby25-x64/bin/wp2txt:23:in `<main>'
        4: from C:/Ruby25-x64/bin/wp2txt:23:in `load'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wp2txt-0.9.1/bin/wp2txt:64:in `<top (required)>'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:219:in `extract_text'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:113:in `prepare'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:113:in `popen': No such file or directory - bzip2 -c -d enwiki-20190820.bz2 (Errno::ENOENT)

i also have tried installing optimist and using it as below. still no luck.

C:\Users\gopal>gem install optimist
Fetching: optimist-3.0.0.gem (100%)
Successfully installed optimist-3.0.0
Parsing documentation for optimist-3.0.0
Installing ri documentation for optimist-3.0.0
Done installing documentation for optimist after 3 seconds
1 gem installed
--------
C:\Users\gopal>optimist --help
'optimist' is not recognized as an internal or external command,
operable program or batch file.
--------

**Comment by yohasebe** [comment]
I am sorry it took me soooo long to get back to you!

Thank you so much for your report. I have overhauled the code and made a major update. I checked the resulting text and believe that the issue you mentioned has been resolved. 

I hope you will give it a try sometime. Thanks again!
