### ISSUE TITLE
`popen': No such file or directory - bzip2 -c -d enwiki-20190820-pages-articles-multistream1.xml-p10p30302.bz2 (Errno::ENOENT)

### ISSUE THREAD

**Issue by Gopal088** [yohasebe/wp2txt#5]
Getting below error. Not sure whats the issue.
c:\Users\gopal\Downloads>wp2txt -i enwiki-20190820.bz2 -o wikitxt 
[DEPRECATION] This gem has been renamed to optimist and will no longer  be supported. Please switch to optimist as soon as possible. 
Traceback (most recent call last): 
5: from C:/Ruby25-x64/bin/wp2txt:23:in <main>' 
4: from C:/Ruby25-x64/bin/wp2txt:23:in load' 
3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wp2txt-0.9.1/bin/wp2txt:64:in <top (required)>' 
2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:219:in extract_text' 
1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:113:in prepare' C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:113:in popen': No such file or directory - bzip2 -c -d enwiki-20190820.bz2 (Errno::ENOENT) 

i also have tried installing optimist and using it as below. still no luck. 

C:\Users\gopal>gem install optimist 
Fetching: optimist-3.0.0.gem (100%) Successfully installed optimist-3.0.0 Parsing documentation for optimist-3.0.0 Installing ri documentation for optimist-3.0.0 Done installing documentation for optimist after 3 seconds 1 gem installed 
--
C:\Users\gopal>optimist --help 'optimist' is not recognized as an internal or external command, operable program or batch file.
--

**Comment by rafaleo** [comment]
Have similar issue:

```
C:\Users\cp>wp2txt -i c:/Users/cp/Downloads/NET/dumps.wikimedia.org_enwikisource-20200220-pages-articles-multistream.xml
.bz2 -o k:/DATA/NLP/wikidump -u 2
[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as
 soon as possible.
Traceback (most recent call last):
        5: from C:/Ruby26-x64/bin/wp2txt:23:in `<main>'
        4: from C:/Ruby26-x64/bin/wp2txt:23:in `load'
        3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/wp2txt-0.9.1/bin/wp2txt:64:in `<top (required)>'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:219:in `extract_text'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:113:in `prepare'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/wp2txt-0.9.1/lib/wp2txt.rb:113:in `popen': No such file or directory - bzip2 -c -
d c:/Users/cp/Downloads/NET/dumps.wikimedia.org_enwikisource-20200220-pages-articles-multistream.xml.bz2 (Errno::ENOENT)
```

The file exists for sure.

**Comment by yohasebe** [comment]
I am sorry for this belated reply! 

To use WP2TXT on Windows, plase install [Bzip2 for Windows](http://gnuwin32.sourceforge.net/packages/bzip2.htm) and set the path so that WP2TXT can use the `bunzip2.exe` command.

Alternatively, you can first extract the Wikipedia dump file yourself using decompression software that supports `bz2` files. Then process the resulting XML file with WP2TXT.
